# Generated by Django 5.1.6 on 2025-02-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sistema_operativo', models.CharField(blank=True, max_length=255, null=True)),
                ('version_sistema', models.CharField(blank=True, max_length=255, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_publica', models.GenericIPAddressField(blank=True, null=True)),
                ('dominio', models.CharField(blank=True, max_length=255, null=True)),
                ('tiempo_de_infeccion_fecha', models.DateField(blank=True, null=True)),
                ('tiempo_de_infeccion_hora', models.TimeField(blank=True, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='maquinas/fotos/')),
                ('archivo_1', models.FileField(blank=True, null=True, upload_to='maquinas/archivos/')),
                ('archivo_2', models.FileField(blank=True, null=True, upload_to='maquinas/archivos/')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_base64', models.TextField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraseñas', to='backend.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaz', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='backend.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='backend.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifis', to='backend.maquina')),
            ],
        ),
    ]
