# Generated by Django 5.1.6 on 2025-02-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='archivo_1',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='archivo_2',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='fotos',
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.BinaryField()),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='backend.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='backend.maquina')),
            ],
        ),
    ]
